### ISSUE TITLE
requestAnimationFrame polyfill should either be removed or safe for server

### ISSUE THREAD

**Issue by cha0s** [a-jie/Proton#63]
I want to be able to run Proton on a server, where `window` doesn't exist. You can still simulate particles even if you don't actually render them.

This is currently not possible, as Proton does `import './polyfill/requestAnimationFrame';`, which throws something like:

```
.../node_modules/proton-js/src/polyfill/requestAnimationFrame.js:9
		for (var x = 0; x < vendors.length && !window.requestAnimationFrame; ++x) {
                                         ^
ReferenceError: window is not defined
    at window (.../node_modules/proton-js/src/polyfill/requestAnimationFrame.js:9:42)
    at .../node_modules/proton-js/src/polyfill/requestAnimationFrame.js:6:3
    at .../node_modules/proton-js/build/proton.min.js:10:84
    at Object.<anonymous> (.../node_modules/proton-js/build/proton.min.js:10:149)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
```

on a server environment.

I don't see that `requestAnimationFrame` is actually used anywhere in the engine. Only the examples.

**Comment by cha0s** [comment]
I recommend total removal as I don't think that a global polyfill for raf is Proton's responsibility.

**Comment by a-jie** [comment]
Very good advice, can I look at the code you submitted tomorrow? Sorry, it’s already late.

**Comment by cha0s** [comment]
Take your time and have a good night

**Comment by a-jie** [comment]
Very good change, I have merged into the master branch (can you help verify all the examples?). I also removed it in proton 4.0.

**Comment by cha0s** [comment]
I did check the examples locally when I was developing the pull request, everything seemed to be working fine!
